"""Add remediation status fields

Revision ID: 10af2bb20af2
Revises: bf3dd7d18a6e
Create Date: 2026-04-04 15:33:49.336157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10af2bb20af2'
down_revision: Union[str, None] = 'bf3dd7d18a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remediation_status', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_finding_remediation_status'), ['remediation_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_remediation_status'))
        batch_op.drop_column('remediation_status')

    # ### end Alembic commands ###
