"""Add PII remediation fields

Revision ID: bf3dd7d18a6e
Revises: 96f2e2b9e675
Create Date: 2026-04-04 12:15:14.025565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3dd7d18a6e'
down_revision: Union[str, None] = '96f2e2b9e675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('remediation_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sample_masked_value', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_column('sample_masked_value')
        batch_op.drop_column('remediation_text')
        batch_op.drop_column('recommendation_type')

    # ### end Alembic commands ###
